"""
Dumps the exact prompts each analysis stage sends to Gemini, to files.

Both stages assemble their prompt at call time from a private ``_build_prompt()``
plus whichever knowledge files are present, so the only faithful way to see what
the model actually receives is to call those builders. This script does that — and
nothing else: it never calls Gemini, never touches Sheets or Drive, and writes
only into ``prompts/``.

Two views per stage, because the injected knowledge dwarfs the instructions
(capability context ~13 KB, the detailed corpus ~168 KB):

  prompts/<stage>_prompt.txt        every instruction verbatim, each injected
                                    knowledge block replaced by a short marker
                                    naming its file and size — readable, diffable
  prompts/<stage>_prompt.full.txt   the same prompt fully expanded, i.e. the bytes
                                    that go over the wire

Both are generated by the real builders from one sample tender row, so a wording
change in either module shows up here on the next run.

Usage:
    python dump_prompts.py                    # dated today
    python dump_prompts.py --date 2026-08-27  # fixed date, for stable diffs
"""
import argparse
import os
import sys
from datetime import datetime, timedelta

from analyzer import analyzer as bid
from analyzer import config as bid_config
from analyzer.onepoint_context import load_onepoint_context
from analyzer.patterns import load_nobid_patterns, load_bid_patterns

from DetailedAnalyzer import detailed_analyzer as detail
from DetailedAnalyzer import config as detail_config
from DetailedAnalyzer.sources import load_corpus

from config import UK_TIMEZONE

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
OUTPUT_DIR = os.path.join(BASE_DIR, "prompts")

# One representative tracker row. Not a real tender — the point is to exercise
# every conditional in the builders (all CONTEXT_FIELDS populated, a live deadline,
# both money columns) so no instruction is missing from the dump merely because a
# field happened to be blank. Edit freely; nothing but this script reads it.
SAMPLE_TENDER = {
    "ID": "SAMPLE-0001",
    "OCID": "ocds-sample-0001",
    "Name": "Provision of a Cloud Data Platform and Analytics Services",
    "Tender Description": (
        "The Authority seeks a supplier to design, build and operate a cloud-based "
        "data platform consolidating operational data from twelve legacy systems, "
        "with Power BI reporting, automated data quality monitoring and knowledge "
        "transfer to in-house staff. Four-year term with an optional two-year extension."
    ),
    "Buyer Name": "Sample County Council",
    "Published On": "2026-08-01",
    "Clarification Due Date": "2026-08-20",
    "Procurement Stage": "Open Tender",
    "Total Contract Value": "GBP 2,400,000",
    "Contract Duration": "48 months",
    "Annual Contract Value": "GBP 600,000",
    "CPV Code": "72000000",
    "CPV Description": "IT services: consulting, software development, Internet and support",
    "Country": "United Kingdom",
    "Locality": "Manchester",
    "SC_Flag": "No",
    "SME_Flag": "Yes",
    "PME_Flag": "No",
}


def _marker(path: str, content: str, description: str) -> str:
    """The stand-in for an injected knowledge block in the skeleton view."""
    rel = os.path.relpath(path, BASE_DIR)
    return (f"<<< {description}\n"
            f"    injected verbatim from {rel} ({len(content):,} chars)\n"
            f"    see the .full.txt dump for the expanded text >>>")


def _write(filename: str, header: list, sections: list):
    """Write one dump file: a header block, then labelled prompt sections."""
    rule = "=" * 80
    parts = [rule] + header + [rule, ""]
    for label, body in sections:
        parts += ["-" * 80, label, "-" * 80,
                  body.strip() if body.strip() else "(empty)", ""]

    path = os.path.join(OUTPUT_DIR, filename)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write("\n".join(parts))
    print(f"  {os.path.relpath(path, BASE_DIR):48s} {os.path.getsize(path):>9,} bytes")


def dump_analyzer(run_dt: datetime):
    """analyzer.analyze_tender() — the Bid / NoBid / TBD scoring call."""
    context = load_onepoint_context()
    nobid = load_nobid_patterns()
    bid_patterns = load_bid_patterns()

    settings = (
        f"model={bid_config.ANALYZER_MODEL}  temperature={bid_config.ANALYZER_TEMPERATURE}  "
        f"max_output_tokens={bid_config.ANALYZER_MAX_TOKENS}  "
        f"thinking_budget={bid_config.ANALYZER_THINKING_BUDGET}  "
        f"response_mime_type=application/json  max_retries={bid_config.ANALYZER_MAX_RETRIES}"
    )

    def header(view):
        return [
            "PS-BidAnalyzer — prompt dump: analyzer.analyze_tender()   [stage 1: scoring]",
            f"View      : {view}",
            "Built by  : analyzer/analyzer.py — _SYSTEM_PROMPT, _build_prompt()",
            f"Settings  : {settings}",
            f"Generated : {run_dt:%Y-%m-%d %H:%M %Z} from the sample tender in dump_prompts.py",
            "Note      : generated file — change the prompt in analyzer/analyzer.py, not here.",
        ]

    expanded = bid._build_prompt(
        SAMPLE_TENDER["Name"], SAMPLE_TENDER["Tender Description"],
        context, nobid, bid_patterns,
    )
    skeleton = bid._build_prompt(
        SAMPLE_TENDER["Name"], SAMPLE_TENDER["Tender Description"],
        _marker(bid_config.ONEPOINT_CONTEXT_FILE, context,
                "ONEPOINT CAPABILITY CONTEXT — the sole basis for judging capability"),
        _marker(bid_config.NOBID_PATTERNS_FILE, nobid,
                "DISTILLED NoBid PRECEDENT — generated by analyzer.maintain_knowledge"),
        _marker(bid_config.BID_PATTERNS_FILE, bid_patterns,
                "DISTILLED Bid PRECEDENT — generated by analyzer.maintain_knowledge"),
    )

    branches = (
        "1. Either precedent block is omitted entirely when its file is absent or "
        "empty, so deleting knowledge/nobid_patterns.md or knowledge/bid_patterns.md "
        "removes that whole section — heading and calibration instruction included — "
        "from the prompt above.\n\n"
        "2. The capability block is always present; with no context file it degrades "
        "to the literal text '(No Onepoint capability context provided.)'.\n\n"
        "3. An empty title AND description never reach the model at all — "
        "analyze_tender() short-circuits to a deterministic NoBid before building "
        "any prompt."
    )

    for filename, view, prompt in (
        ("analyzer_prompt.txt",
         "skeleton — injected knowledge shown as markers", skeleton),
        ("analyzer_prompt.full.txt",
         "fully expanded — the bytes sent to Gemini", expanded),
    ):
        _write(filename, header(view), [
            ("SYSTEM INSTRUCTION   (GenerateContentConfig.system_instruction)",
             bid._SYSTEM_PROMPT),
            ("USER PROMPT   (generate_content contents=)", prompt),
            ("BRANCHES NOT SHOWN ABOVE", branches),
        ])


def dump_detailed_analyzer(run_dt: datetime):
    """DetailedAnalyzer.analyse_tender_detail() — the full qualification brief."""
    context = detail.load_onepoint_context()
    corpus = load_corpus()

    # Give the sample a live deadline relative to the dump date, so the timeline
    # block reads sensibly whenever this is run instead of drifting into EXPIRED.
    row = dict(SAMPLE_TENDER)
    row["Tender Due Date"] = (run_dt + timedelta(days=21)).strftime("%Y-%m-%d")

    facts = detail._format_tender_facts(row)
    deterministic = detail._deterministic_fields(row, run_dt)
    timeline = detail._timeline_block(deterministic)

    # The tender pack is per-tender and read from Drive at run time, so there is
    # nothing local to expand it from. Both views therefore carry a marker in its
    # place — the instructions wrapped around it are the real ones — and the
    # no-pack branch is reproduced below the prompt.
    pack_marker = (
        "<<< THIS TENDER'S OWN PACK — the buyer's published documents\n"
        "    injected verbatim, one '=== DOCUMENT: <name> ===' section per file,\n"
        f"    read from Drive at run time (folder {detail_config.TENDER_DOCS_FOLDER_ID},\n"
        f"    matched on {detail_config.TENDER_DOCS_MATCH_FIELD}); a document trimmed to\n"
        "    fit the analysis budget carries an explicit truncation note >>>"
    )
    pack_absent_note = (
        "No tender pack was available for this tender — no documents have been "
        "uploaded for it, so this assessment rests on the tender summary above "
        "alone. Say so where a question can only be answered from the tender "
        "documents (evaluation weightings, mandatory requirements, contractual "
        "terms) rather than inferring an answer."
    )

    settings = (
        f"model={detail_config.DETAIL_MODEL}  temperature={detail_config.DETAIL_TEMPERATURE}  "
        f"max_output_tokens={detail_config.DETAIL_MAX_TOKENS}  "
        f"thinking_budget={detail_config.DETAIL_THINKING_BUDGET}  "
        f"response_mime_type=application/json  max_retries={detail_config.DETAIL_MAX_RETRIES}"
    )

    def header(view):
        return [
            "PS-BidAnalyzer — prompt dump: DetailedAnalyzer.analyse_tender_detail()",
            "                              [stage 2: qualification brief]",
            f"View      : {view}",
            "Built by  : DetailedAnalyzer/detailed_analyzer.py — _SYSTEM_PROMPT, _build_prompt()",
            "            JSON field list emitted from DetailedAnalyzer/template.py",
            f"Settings  : {settings}",
            f"Generated : {run_dt:%Y-%m-%d %H:%M %Z} from the sample tender in dump_prompts.py",
            "Note      : generated file — change the prompt in DetailedAnalyzer/detailed_analyzer.py.",
        ]

    expanded = detail._build_prompt(
        row["Name"], row["Tender Description"], facts, context,
        corpus, timeline, pack_marker, "",
    )
    skeleton = detail._build_prompt(
        row["Name"], row["Tender Description"], facts,
        _marker(detail_config.ONEPOINT_CONTEXT_FILE, context,
                "ONEPOINT CAPABILITY CONTEXT — shared with stage 1, hand-authored"),
        _marker(detail_config.CORPUS_FILE, corpus,
                "ONEPOINT SOURCE CORPUS — built by DetailedAnalyzer.sources"),
        timeline, pack_marker, "",
    )

    # The branches the builders can take that the prompt above does not show.
    expired = dict(deterministic)
    expired["Time Remaining"] = "Deadline passed 22 day(s) ago (05/08/2026)"
    expired["Urgency Status"] = detail.URGENCY_BANDS[0][1]
    branches = (
        "1. NO TENDER PACK — when no documents have been uploaded for the tender, "
        "the whole pack block above (heading, the 'THE PACK WINS' instruction and "
        "all) is replaced by this single paragraph:\n\n"
        f"{pack_absent_note}\n\n"
        "2. DEADLINE ALREADY PASSED — _timeline_block() appends a fourth line to "
        "the Timeline section, making it read:\n\n"
        f"{detail._timeline_block(expired)}\n\n"
        "3. The corpus block is omitted entirely when the corpus has never been "
        "built. The capability block is always present, degrading to "
        "'(No Onepoint capability context provided.)'.\n\n"
        "4. The deterministic template rows (submission deadline, client name, "
        "reference, location, time remaining, urgency) are filled from the tracker "
        "row and the clock, never asked of the model — which is why they are absent "
        "from the JSON field list above."
    )

    for filename, view, prompt in (
        ("detailedanalyzer_prompt.txt",
         "skeleton — injected knowledge shown as markers", skeleton),
        ("detailedanalyzer_prompt.full.txt",
         "fully expanded — as sent to Gemini, bar the per-tender pack", expanded),
    ):
        _write(filename, header(view), [
            ("SYSTEM INSTRUCTION   (GenerateContentConfig.system_instruction)",
             detail._SYSTEM_PROMPT),
            ("USER PROMPT   (generate_content contents=)", prompt),
            ("BRANCHES NOT SHOWN ABOVE", branches),
        ])


def main():
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    parser = argparse.ArgumentParser(
        description="Dump each analysis stage's Gemini prompt to prompts/.")
    parser.add_argument("--date", help="Dump as at YYYY-MM-DD (default: today). Fix it "
                                      "for byte-stable diffs between runs.")
    args = parser.parse_args()

    if args.date:
        run_dt = UK_TIMEZONE.localize(datetime.strptime(args.date, "%Y-%m-%d"))
    else:
        run_dt = datetime.now(UK_TIMEZONE)

    os.makedirs(OUTPUT_DIR, exist_ok=True)
    print("Writing prompt dumps:")
    dump_analyzer(run_dt)
    dump_detailed_analyzer(run_dt)


if __name__ == "__main__":
    main()
